spring:
  application:
    name: epam-bank-service
  mvc:
    hidden method:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/bankdb
    hikari:
      connection-timeout: 1000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: false
server:
  port: 8081

jwt:
  secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.epam.bank: DEBUG
    org.springframework.security: DEBUG