spring:
  application:
    name: epam-bank-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: appuser
    password: secret123
    url: jdbc:postgresql://localhost:5432/bankdb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

jwt:
  secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24 hours

encryption:
  secret-key: ${ENCRYPTION_KEY:MySecretKey12345}

logging:
  level:
    com.epam.bank: DEBUG
    org.springframework.security: DEBUG